image: python:latest
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
cache:
  paths:
    - .cache/pip
    - venv
before_script:
  - python --version
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - pip install -r requirements.txt
test:
  script:
    - pytest --junitxml report.xml tests/test_basic.py
    - pytest --junitxml report.xml tests/test_web.py
    - pytest --junitxml report.xml tests/test_user_model.py

